### ISSUE TITLE
cameraIp should (ideally ;) be able to use DNS names, in addition to IP addresses

### ISSUE THREAD

**Issue by poeml** [marcokeur/pimatic-foscam#1]
Hi! I discovered your plugin and am thrilled to try it out with a Foscam FI9803P IP camera.

I use this config:

```
   {
      "id": "fc1-new",
      "class": "IpCamera",
      "name": "Foscam fc1-new Test",
      "username": "USER",
      "password": "PASS",
      "cameraIp": "CAM.MY.DOMAIN",
      "cameraPort": 88,
      "wsPort": 9500
}
```

pimatic doesn't start any longer, though. It seems to silently crash. Only when I run it in the foreground, it gives the following error when exiting:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
zsh: exit 8     sudo node_modules/pimatic/pimatic.js
```

It crashes at a relatively early point (only few lines logged up to this point).

When I use a DNS name instead of an IP address, it gets much farther with the starting, and I see a promising line `Started WS stream at port 9500 from origin rtsp:///...` :-)

It crashes afterwards, though, with the exact same error message, which will be subject of a further issue.

**Comment by marcokeur** [comment]
Hi Peter,

I've been looking at this, but i can't reproduce it. I do use dns names internally and it works like a charm.
Does your domain resolve to your camera correctly? 

Marco

**Comment by poeml** [comment]
Hi Marco,

you are right. It was not the problem. DNS resolution now works for me, too.  It must have been another problem in the config I was testing. 

I tried to reproduce with a non-existing DNS name, and that yields a rather different error:

`
TypeError: Cannot read property 'CGI_Result' of undefined
    at /home/pi/pimatic-app/node_modules/pimatic-foscam/foscam.coffee:107:24
    at Parser.<anonymous> (/home/pi/pimatic-app/node_modules/xml2js/lib/xml2js.js:488:18)
    at Parser.emit (events.js:95:17)
    at Parser.exports.Parser.Parser.parseString (/home/pi/pimatic-app/node_modules/xml2js/lib/xml2js.js:507:16)
    at Parser.parseString (/home/pi/pimatic-app/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/home/pi/pimatic-app/node_modules/xml2js/lib/xml2js.js:535:19)
    at Request._callback (/home/pi/pimatic-app/node_modules/pimatic-foscam/foscam.coffee:106:9)
    at self.callback (/usr/lib/nodejs/request/index.js:148:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/usr/lib/nodejs/request/index.js:258:10)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.emit (events.js:95:17)
    at net.js:833:16
    at process._tickDomainCallback (node.js:463:13)
`

This error message is still a bit misleading, but that probably shouldn't  have high priority at this stage. Feel free to close the issue!
